### ISSUE TITLE
Legit?

### ISSUE THREAD

**Issue by drdreo** [RumbleMike/ValorantRankedPoints#2]
This repo was shown during the onscreen stream. We had like a group analysis of the code. 
Easiest thing to do is ask. Is this legit without any account phishing?

**Comment by ar1a** [comment]
if this was account phishing then they wouldnt tell you they were

**Comment by RumbleMike** [comment]
If this was to steal account info, it would first off ruin my reputation on both my name and my Valorleaks account. This is also why I made the code public, so anyone can view how it works. Otherwise, I see other people building their own tools with some of the code. I cannot say those are safe, I can only speak for myself.

**Comment by Rehkloos** [comment]
Anyone who understands code can see this is using account credentials to be used in authentication check with riot servers and call the api

**Comment by BobbyESP** [comment]
This is completly safe, and if u see the Source Code, all what the program does is call Riot servers to get the Token of your account and put it in the API  to get the matches history. After this, the program shapes the answer to be understandable by all and in a simple way
